name: mybinder-env
channels:
  - conda-forge
  - bioconda  # if you need bioinformatics tools
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pandas
  - pip
  - axel
  - orthofinder
  - pip:
      - sequana
      - wget
